### ISSUE TITLE
Create text label when a VOpp is already finished/past the date

### ISSUE THREAD

**Issue by ridvanbaluyos** [ivolunteerph/ui-studies#10]
When a VOpp is already past the event date, put a label or an indicator that it is already finished.

The current implementation has no label or indicator but only removes the button.
![screen shot 2014-10-22 at 4 08 36 am](https://cloud.githubusercontent.com/assets/156903/4726010/607df78c-595e-11e4-9707-7fb9052c320a.png)

Our implementation displays a negative value.
![screen shot 2014-10-22 at 4 12 09 am](https://cloud.githubusercontent.com/assets/156903/4726040/9b269858-595e-11e4-9b60-5f61fce388bc.png)

**Comment by justincalingasan** [comment]
committed to 3e51795. Maybe we can remove the whole row of data (days left, volunteer count) when the event is done, even the volunteers needed too

**Comment by ridvanbaluyos** [comment]
verified. merged to backend at https://github.com/ivolunteerph/ivolunteerph/commit/c83bb5e0353ac3d689959a87712dbc860c1dd988
Ridvan Baluyos ridvanbaluyos authored 3 minutes ago

![screen shot 2014-10-25 at 11 42 25 pm](https://cloud.githubusercontent.com/assets/156903/4780214/a3d2c678-5c5d-11e4-9f5e-6b7a9e57f3db.png)
