### ISSUE TITLE
Create a list of people who volunteered in a VOpp

### ISSUE THREAD

**Issue by ridvanbaluyos** [ivolunteerph/ui-studies#11]
We can possibly put the list below the Volunteer button. This is viewable only for admins and owners of the org that the event belongs to.

![screen shot 2014-10-22 at 4 46 18 am](https://cloud.githubusercontent.com/assets/156903/4726536/69fe237c-5963-11e4-87a6-0b63463384b0.png)

**Comment by justincalingasan** [comment]
committed to 16ae6c1. Placed the list below the event description just for source order's sake (the page will be long if it's placed after the volunteer button), but it's open for suggestions. Either through modals or a collapsible div.

**Comment by ridvanbaluyos** [comment]
deployed at https://github.com/ivolunteerph/ivolunteerph/commit/453d0ce189d7517d7277b4a0c837ca30ffb48433

Modified the columns: Name, Email, Mobile Number

![screen shot 2014-10-27 at 1 39 48 am](https://cloud.githubusercontent.com/assets/156903/4783825/8dc5b9f0-5d37-11e4-9039-025804b4e259.png)

**Comment by ridvanbaluyos** [comment]
Let's make it a modal list. Based from the existing implementation we need to include the Full Name, Email, and Mobile Address. It doesn't fit. :D

![screen shot 2014-10-27 at 2 13 28 am](https://cloud.githubusercontent.com/assets/156903/4783937/d3b7ca26-5d3b-11e4-837c-842de811897c.png)

**Comment by justincalingasan** [comment]
Made the list full-width. Committed to 5ec99ee

**Comment by ridvanbaluyos** [comment]
Closing.

![screen shot 2014-11-06 at 11 32 36 pm](https://cloud.githubusercontent.com/assets/156903/4938270/3605ee42-65ca-11e4-88ca-e6890988d468.png)
