### ISSUE TITLE
Create a Volunteer Profile Page

### ISSUE THREAD

**Issue by ridvanbaluyos** [ivolunteerph/ui-studies#14]
Create a page wherein other users (logged in and not) can view the profile of a volunteer.

Something similar to this: 
![screen shot 2014-11-06 at 11 17 13 pm](https://cloud.githubusercontent.com/assets/156903/4937952/08358aec-65c8-11e4-8292-861d8946337e.png)

But let's make it more "presentable" :D

**Comment by justincalingasan** [comment]
Committed to 84a7e44. We can omit "Edit Profile" link if user is a guest or not the same user as the profile

Additional css change in 87db101. Apologies!

**Comment by ridvanbaluyos** [comment]
thanks shir! committed at https://github.com/ivolunteerph/ivolunteerph/commit/866669444e0330b5602ebc894e723568c2eb0576

![screen shot 2014-11-12 at 2 08 58 am](https://cloud.githubusercontent.com/assets/156903/4998173/e3a1c234-6a10-11e4-81c6-505c9e05a85f.png)
