### ISSUE TITLE
Create a Manage Events Page

### ISSUE THREAD

**Issue by ridvanbaluyos** [ivolunteerph/ui-studies#15]
Something like this:
![screen shot 2014-11-06 at 11 15 26 pm](https://cloud.githubusercontent.com/assets/156903/4937964/233c18b0-65c8-11e4-8bf4-68b0b96cbb5c.png)

But there are actions buttons such as Delete and Edit.

**Comment by justincalingasan** [comment]
Committed to 7397c8f

**Comment by ridvanbaluyos** [comment]
thanks shir @justincalingasan
