### ISSUE TITLE
Create an Edit VOpps link

### ISSUE THREAD

**Issue by ridvanbaluyos** [ivolunteerph/ui-studies#17]
VOpp Details:
![screen shot 2014-11-10 at 7 06 27 am](https://cloud.githubusercontent.com/assets/156903/4969614/1e173d20-6865-11e4-9c2e-37b0a2330dd8.png)

**Comment by justincalingasan** [comment]
Committed to c9d9f04. Added link beside title, let me know if this is ok.

**Comment by ridvanbaluyos** [comment]
thanks shir! committed to https://github.com/ivolunteerph/ivolunteerph/commit/866669444e0330b5602ebc894e723568c2eb0576

![screen shot 2014-11-12 at 1 43 20 am](https://cloud.githubusercontent.com/assets/156903/4997835/556666f8-6a0d-11e4-84dd-0099547c081e.png)
