### ISSUE TITLE
Link to Dashboard Page

### ISSUE THREAD

**Issue by ridvanbaluyos** [ivolunteerph/ui-studies#3]
Should we put a link to the Dashboard page somewhere?

**Comment by justincalingasan** [comment]
Ideally the username link in the navigation will be the link to the dashboard

**Comment by ridvanbaluyos** [comment]
hi shir @justincalingasan, clicking the username link triggers the dropdown menu. need help. :D :smile_cat:

**Comment by justincalingasan** [comment]
Hi sir @ridvanbaluyos , added a "Dashboard" link in the menu. Commit d2807f9

**Comment by ridvanbaluyos** [comment]
thanks shir!
