### ISSUE TITLE
Address overlaps the description

### ISSUE THREAD

**Issue by ridvanbaluyos** [ivolunteerph/ui-studies#8]
In the VOpps listings page, the address information overlaps the description.

![screen shot 2014-10-20 at 2 51 49 am](https://cloud.githubusercontent.com/assets/156903/4694239/303ab694-57c1-11e4-8436-b19b409da03c.png)

**Comment by justincalingasan** [comment]
committed to 65cc283

**Comment by ridvanbaluyos** [comment]
would it be possible to wrap the text instead of ellipsis? volunteers need the complete information of the address.

**Comment by justincalingasan** [comment]
acknowledged, changes in 1fc9169.

**Comment by ridvanbaluyos** [comment]
fixed commited at https://github.com/ivolunteerph/ivolunteerph/commit/bf592082bec2f5f30e51fbc567d81adcdfa05fc0

![Uploading Screen Shot 2014-10-26 at 5.52.06 PM.png . . .]()
