### ISSUE TITLE
Create button label for "Already Joined"

### ISSUE THREAD

**Issue by ridvanbaluyos** [ivolunteerph/ui-studies#9]
When a user has already joined the event, the "Volunteer" button label should be replaced by "Already Joined" text. Button must be disabled. Or possibly just a text?

![screen shot 2014-10-20 at 3 18 04 am](https://cloud.githubusercontent.com/assets/156903/4694340/c4bc221e-57c4-11e4-8208-4419e6d1ab6b.png)

**Comment by justincalingasan** [comment]
_Edit_ committed to 4dc1100

**Comment by ridvanbaluyos** [comment]
verified. merged to backend at https://github.com/ivolunteerph/ivolunteerph/commit/c83bb5e0353ac3d689959a87712dbc860c1dd988
Ridvan Baluyos ridvanbaluyos authored 3 minutes ago

![screen shot 2014-10-25 at 11 08 11 pm](https://cloud.githubusercontent.com/assets/156903/4780109/c68bd6d2-5c58-11e4-9f97-8a7f6094262b.png)
